Models/Funcionario.cs
using System;
using System.Globalization;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace FuncionariosIN3.Models
{
    [Table("tbfuncionario")]
    public class Funcionario
    {
        [Key][System.ComponentModel.DisplayName("Código")]
        public int cdFuncionario { get; set; }
        [System.ComponentModel.DisplayName("Nome do Funcionário")]
        public string dsNome { get; set; }
        public string dsEmail { get; set; }
        public string dsCPF { get; set; }
        [System.ComponentModel.DisplayName("Admissão")]
        public DateTime dtAdmissao { get; set; }
        public DateTime dtNascimento { get; set; }
        public int biAtivo { get; set; }
        [System.ComponentModel.DisplayName("Descrição do Cargo")]
        public int cdCargo { get; set; }
        [System.ComponentModel.DisplayName("Salário")]
        public decimal vlSalario { get; set; }
        public string dsObservacao { get; set; }
        public DateTime dtSysInclusao { get; set; }
        public DateTime dtSysAlteracao { get; set; }

    }

    public class FuncionarioDBContext : DbContext
    {
        public DbSet<Funcionario> Funcionarios { get; set; }
    }
}

Controllers/FuncionariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FuncionariosIN3.Models;

namespace FuncionariosIN3.Controllers
{
    public class FuncionariosController : Controller
    {
        private FuncionarioDBContext db = new FuncionarioDBContext();

        // GET: Funcionarios
        public ActionResult Index()
        {
            return View(db.Funcionarios.ToList());
        }

        // GET: Funcionarios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Funcionario funcionario = db.Funcionarios.Find(id);
            if (funcionario == null)
            {
                return HttpNotFound();
            }
            return View(funcionario);
        }

        // GET: Funcionarios/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Funcionarios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "cdFuncionario,dsNome,dsEmail,dsCPF,dtAdmissao,dtNascimento,biAtivo,cdCargo,vlSalario,dsObservacao,dtSysInclusao,dtSysAlteracao")] Funcionario funcionario)
        {
            if (ModelState.IsValid)
            {
                db.Funcionarios.Add(funcionario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(funcionario);
        }

        // GET: Funcionarios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Funcionario funcionario = db.Funcionarios.Find(id);
            if (funcionario == null)
            {
                return HttpNotFound();
            }
            return View(funcionario);
        }

        // POST: Funcionarios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "cdFuncionario,dsNome,dsEmail,dsCPF,dtAdmissao,dtNascimento,biAtivo,cdCargo,vlSalario,dsObservacao,dtSysInclusao,dtSysAlteracao")] Funcionario funcionario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(funcionario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(funcionario);
        }

        // GET: Funcionarios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Funcionario funcionario = db.Funcionarios.Find(id);
            if (funcionario == null)
            {
                return HttpNotFound();
            }
            return View(funcionario);
        }

        // POST: Funcionarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Funcionario funcionario = db.Funcionarios.Find(id);
            db.Funcionarios.Remove(funcionario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Funcionarios/Create.cshtml
@model FuncionariosIN3.Models.Funcionario

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Funcionario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.dsNome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dsNome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dsNome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dsEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dsEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dsEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dsCPF, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dsCPF, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dsCPF, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dtAdmissao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dtAdmissao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dtAdmissao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dtNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dtNascimento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dtNascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.biAtivo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.biAtivo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.biAtivo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cdCargo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cdCargo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cdCargo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.vlSalario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.vlSalario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.vlSalario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dsObservacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dsObservacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dsObservacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dtSysInclusao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dtSysInclusao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dtSysInclusao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dtSysAlteracao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dtSysAlteracao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dtSysAlteracao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Funcionarios/Delete.cshtml
@model FuncionariosIN3.Models.Funcionario

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Funcionario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.dsNome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dsNome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dsEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dsEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dsCPF)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dsCPF)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dtAdmissao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dtAdmissao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dtNascimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dtNascimento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.biAtivo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.biAtivo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cdCargo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cdCargo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vlSalario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vlSalario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dsObservacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dsObservacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dtSysInclusao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dtSysInclusao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dtSysAlteracao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dtSysAlteracao)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Funcionarios/Details.cshtml
@model FuncionariosIN3.Models.Funcionario

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Funcionario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.dsNome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dsNome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dsEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dsEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dsCPF)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dsCPF)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dtAdmissao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dtAdmissao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dtNascimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dtNascimento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.biAtivo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.biAtivo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cdCargo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cdCargo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vlSalario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vlSalario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dsObservacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dsObservacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dtSysInclusao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dtSysInclusao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dtSysAlteracao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dtSysAlteracao)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.cdFuncionario }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Funcionarios/Edit.cshtml
@model FuncionariosIN3.Models.Funcionario

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Funcionario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.cdFuncionario)

        <div class="form-group">
            @Html.LabelFor(model => model.dsNome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dsNome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dsNome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dsEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dsEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dsEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dsCPF, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dsCPF, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dsCPF, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dtAdmissao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dtAdmissao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dtAdmissao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dtNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dtNascimento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dtNascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.biAtivo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.biAtivo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.biAtivo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cdCargo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cdCargo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cdCargo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.vlSalario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.vlSalario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.vlSalario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dsObservacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dsObservacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dsObservacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dtSysInclusao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dtSysInclusao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dtSysInclusao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dtSysAlteracao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dtSysAlteracao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dtSysAlteracao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Funcionarios/Index.cshtml
@model IEnumerable<FuncionariosIN3.Models.Funcionario>

@{
    ViewBag.Title = "Index";
}

<label style="color:red; visibility:hidden">Mensagem</label>

<div class="panel panel-default">
    <table class="table">
        <thead>
            <tr>
                <th style="color: cornflowerblue; width:250px">Opções de Pesquisa</th>
                <th style="color: cornflowerblue; width:250px">&nbsp;&nbsp;&nbsp;Informação a Pesquisar</th>
                <th style="color: cornflowerblue; width:250px">Registro</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>
                    <div class="dropdown">
                        
                    </div>
                    <div class="dropdown">
                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                            Dropdown
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">

                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>

                    </div>
                </th>
                <th>
                    <div class="col-lg-9">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search for...">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">Go!</button>
                                <button class="btn btn-default" type="button">Go!</button>
                                <button class="btn btn-default" type="button">Go!</button>
                            </span>
                        </div><!-- /input-group -->
                    </div><!-- /.col-lg-6 -->
                </th>
                <th>
                    <input type="text" class="form-control" placeholder="Search for...">
                </th>
            </tr>
        </tbody>
    </table>
</div>

<div class="panel panel-default">
    <table class="table">
        <tr>
            <th style="color: cornflowerblue;">
                @Html.DisplayNameFor(model => model.cdFuncionario)
            </th>
            <th style="color: cornflowerblue;">
                @Html.DisplayNameFor(model => model.dsNome)
            </th>
            <th style="color: cornflowerblue;">
                @Html.DisplayNameFor(model => model.dtAdmissao)
            </th>
            <th style="color: cornflowerblue;">
                @Html.DisplayNameFor(model => model.cdCargo)
            </th>
            <th style="color: cornflowerblue;">
                @Html.DisplayNameFor(model => model.vlSalario)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.cdFuncionario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.dsNome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.dtAdmissao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.cdCargo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.vlSalario)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.cdFuncionario }) |
                    @Html.ActionLink("Details", "Details", new { id = item.cdFuncionario }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.cdFuncionario })
                </td>
            </tr>
        }

    </table>
    </div>
    <p>
        <a href="@Url.Action("Create", "Funcionarios")" class="btn btn-primary">
            Incluir
        </a>
        
    </p>